// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/assets/FloAvatar.js"
    | "/assets/alien-avatar.js"
    | "/assets/avatar-manager.js"
    | "/assets/avatar-renderer.js"
    | "/assets/dragon-avatar.js"
    | "/assets/ghost-avatar.js"
    | "/assets/panda-avatar.js"
    | "/assets/robot-avatar.js"
    | "/background.js"
    | "/content-old.js"
    | "/content-scripts/content.js"
    | "/icons/icon-16.png"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
